-- Create comprehensive lead logging table
CREATE TABLE IF NOT EXISTS lead_logs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    lead_id INT,
    round_robin_id INT,
    participant_id INT,
    event_type ENUM('lead_received', 'lead_assigned', 'discord_attempt', 'discord_success', 'discord_failure', 'error', 'webhook_received') NOT NULL,
    status ENUM('success', 'failure', 'warning', 'info') DEFAULT 'info',
    message TEXT,
    details JSON,
    error_details TEXT,
    source_url VARCHAR(500),
    ip_address VARCHAR(45),
    user_agent TEXT,
    response_time_ms INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL,
    FOREIGN KEY (round_robin_id) REFERENCES round_robins(id) ON DELETE CASCADE,
    FOREIGN KEY (participant_id) REFERENCES rr_participants(id) ON DELETE SET NULL,
    INDEX idx_lead_logs_lead_id (lead_id),
    INDEX idx_lead_logs_rr_id (round_robin_id),
    INDEX idx_lead_logs_event_type (event_type),
    INDEX idx_lead_logs_status (status),
    INDEX idx_lead_logs_created_at (created_at)
);